const LEDGER_URL="data/workouts.json";
const byId=id=>document.getElementById(id);
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const safeUrl=value=>typeof value==="string"&&/^https:\/\//.test(value)?value:null;
const kg=value=>`${Number(value||0).toLocaleString(undefined,{maximumFractionDigits:1})} kg`;
const volume=workout=>(workout.sets||[]).reduce((sum,set)=>sum+Number(set.weightKg||0)*Number(set.reps||0),0);
const streak=workouts=>{const dates=new Set(workouts.map(w=>w.date));let cursor=new Date(),count=0;while(dates.has(cursor.toISOString().slice(0,10))){count++;cursor.setUTCDate(cursor.getUTCDate()-1)}return count};
function renderRecords(records){const target=byId("records-list");if(!records.length){target.innerHTML='<p class="muted">No records yet. Merge a PR to start the ledger.</p>';return}target.innerHTML=records.map(record=>`<article class="record-card"><h3>${escapeHtml(record.exercise)}</h3><div class="record-value">${escapeHtml(record.value)} ${escapeHtml(record.unit||"")}</div><div class="record-meta">${escapeHtml(record.metric||"Personal record")} · ${escapeHtml(record.date||"")}</div>${safeUrl(record.prUrl)?`<a href="${record.prUrl}" target="_blank" rel="noreferrer">View merged PR ↗</a>`:""}</article>`).join("")}
function renderHistory(workouts){const target=byId("history-list");target.innerHTML=workouts.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,20).map(workout=>`<article class="session"><time>${escapeHtml(workout.date)}</time><div><h3>${escapeHtml(workout.name||"Workout")}</h3><p>${(workout.sets||[]).length} sets</p></div><span class="volume">${kg(volume(workout))}</span></article>`).join("")||'<p class="muted">No workouts yet.</p>'}
function render(ledger){const workouts=Array.isArray(ledger.workouts)?ledger.workouts:[],records=Array.isArray(ledger.records)?ledger.records:[];const currentStreak=streak(workouts);byId("workout-count").textContent=workouts.length;byId("volume-total").textContent=kg(workouts.reduce((sum,w)=>sum+volume(w),0));byId("record-count").textContent=records.length;byId("streak-count").textContent=`${currentStreak} day${currentStreak===1?"":"s"}`;byId("last-updated").textContent=ledger.updatedAt?`updated ${new Date(ledger.updatedAt).toLocaleDateString()}`:"";renderRecords(records);renderHistory(workouts)}
fetch(LEDGER_URL,{cache:"no-store"}).then(response=>{if(!response.ok)throw new Error("ledger unavailable");return response.json()}).then(render).catch(error=>{console.error(error);byId("load-error").hidden=false});
