const LEDGER_URL="data/workouts.json";
const byId=id=>document.getElementById(id);
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const safeUrl=value=>typeof value==="string"&&/^https:\/\//.test(value)?value:null;
const kg=value=>`${Number(value||0).toLocaleString(undefined,{maximumFractionDigits:1})} kg`;
const volume=workout=>(workout.sets||[]).reduce((sum,set)=>sum+Number(set.weightKg||0)*Number(set.reps||0),0);
const streak=workouts=>{const dates=new Set(workouts.map(w=>w.date));let cursor=new Date(),count=0;while(dates.has(cursor.toISOString().slice(0,10))){count++;cursor.setUTCDate(cursor.getUTCDate()-1)}return count};
const compound=[["Barbell bench press",/bench/i,"weightKg","kg"],["Barbell squat",/squat/i,"weightKg","kg"],["Deadlift",/deadlift/i,"weightKg","kg"],["Dumbbell press",/dumbbell.*press|db.*press/i,"weightKg","kg"],["Pull-up",/pull.?up/i,"reps","reps"]];
function derivedRecords(workouts){return compound.map(([label,pattern,field,unit])=>{const candidates=[];for(const workout of workouts)for(const set of workout.sets||[])if(pattern.test(set.exercise||""))candidates.push({value:Number(set[field]||0),date:workout.date});if(!candidates.length)return null;const best=candidates.reduce((a,b)=>b.value>a.value?b:a);return {exercise:label,value:best.value,unit,metric:field==="reps"?"max reps":"heaviest set",date:best.date}}).filter(Boolean)}
function renderRecords(records,workouts){const target=byId("records-list");const derived=derivedRecords(workouts),explicit=new Map(records.map(record=>[record.exercise,record])),all=derived.map(record=>explicit.get(record.exercise)||record);for(const record of records)if(!all.some(item=>item.exercise===record.exercise))all.push(record);if(!all.length){target.innerHTML='<p class="muted">No compound records yet. Merge a workout PR to start the ledger.</p>';return}target.innerHTML=all.map(record=>`<article class="record-card"><h3>${escapeHtml(record.exercise)}</h3><div class="record-value">${escapeHtml(record.value)} ${escapeHtml(record.unit||"")}</div><div class="record-meta">${escapeHtml(record.metric||"Personal record")} · ${escapeHtml(record.date||"")}</div>${safeUrl(record.prUrl)?`<a href="${record.prUrl}" target="_blank" rel="noreferrer">View merged PR ↗</a>`:""}</article>`).join("")}
function renderHistory(workouts){const target=byId("history-list");target.innerHTML=workouts.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,20).map(workout=>{const sets=(workout.sets||[]).map((set,index)=>{const reps=`${escapeHtml(set.reps||0)} reps`;const load=Number(set.weightKg||0)>0?`${escapeHtml(set.weightKg)} kg × ${reps}`:reps;return `<div class="set-row"><span>${index+1}. ${escapeHtml(set.exercise||"Exercise")}</span><b>${load}</b></div>`}).join("");return `<article class="session"><time>${escapeHtml(workout.date)}</time><div><h3>${escapeHtml(workout.name||"Workout")}</h3><p>${(workout.sets||[]).length} sets</p><div class="set-list">${sets}</div></div></article>`}).join("")||'<p class="muted">No workouts yet.</p>'}
function render(ledger){const workouts=Array.isArray(ledger.workouts)?ledger.workouts:[],records=Array.isArray(ledger.records)?ledger.records:[],derived=derivedRecords(workouts),currentStreak=streak(workouts);byId("workout-count").textContent=workouts.length;byId("volume-total").textContent=kg(workouts.reduce((sum,w)=>sum+volume(w),0));byId("record-count").textContent=derived.length+records.filter(record=>!derived.some(item=>item.exercise===record.exercise)).length;byId("streak-count").textContent=`${currentStreak} day${currentStreak===1?"":"s"}`;byId("last-updated").textContent=ledger.updatedAt?`updated ${new Date(ledger.updatedAt).toLocaleDateString()}`:"";renderRecords(records,workouts);renderHistory(workouts)}
fetch(LEDGER_URL,{cache:"no-store"}).then(response=>{if(!response.ok)throw new Error("ledger unavailable");return response.json()}).then(render).catch(error=>{console.error(error);byId("load-error").hidden=false});
